### set timer
POST {{api}}/timers
Content-Type: application/json

{
  "url": "https://webhook.site/e2faa3ee-3f52-4822-9ed7-f58ee4fa23cf",
  "hours": 1,
  "minutes": 0,
  "seconds": 0
}

> {% client.global.set("timerID", response.body["id"]); %}

### get timer
GET {{api}}/timers/{{timerID}}
Content-Type: application/json