### create cart
POST {{cart-api}}/carts
Authorisation: Key {{key}}
Content-Type: application/json

> {% client.global.set("cartID", response.body["id"]); %}

### add product to cart
POST {{cart-api}}/carts/{{cartID}}/items
Authorisation: Key {{key}}
Content-Type: application/json

{
  "product_id" :1,
  "quantity": 1,
  "price": 10.50
}

> {%  client.global.set("itemID", response.body["id"]); %}


### remove item from cart
DELETE {{cart-api}}/items/{{itemID}}
Authorisation: Key {{key}}
Content-Type: application/json

### empty cart
DELETE {{cart-api}}/carts/{{cartID}}/items
Authorisation: Key {{key}}
Content-Type: application/json

